### ISSUE TITLE
Cannot start anigrab

### ISSUE THREAD

**Issue by Akianonymus** [ngomile/anigrab#4]
After a fresh install, it shows this error

https://del.dog/odunilenga

After manually creating the ~/.config/anigrab dir, this error disappears

**Comment by ngomile** [comment]
@Akianonymus  Please provide an image of the error and try to follow the format of the issue template. But the problem is that it wasn't finding the directory right? The link you've provided isn't working for me. And just having the images posted here on github is more convenient.

**Comment by AbdullahM0hamed** [comment]
@ngomile I'm not sure why they chose to use another site, but this is what it contained:

```
internal/fs/utils.js:298
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/root/.config/anigrab/cookies.json'
    at Object.openSync (fs.js:465:3)
    at Object.writeFileSync (fs.js:1416:35)
    at Object.<anonymous> (/usr/lib/node_modules/anigrab/src/request.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/lib/node_modules/anigrab/src/utils.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/lib/node_modules/anigrab/src/cli/index.js:23:5)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/.config/anigrab/cookies.json'
}

**Comment by ngomile** [comment]
I've attempted to fix this in the newer version. Can y'all try that and see if it works.

**Comment by Akianonymus** [comment]
My, i should have posted logs here instead of that site.

Anyway, it works now.
